### ISSUE TITLE
Add releases for darwin and linux

### ISSUE THREAD

**Issue by KeisukeYamashita** [solo-io/autopilot#11] opened 2019-11-24 20:05 UTC
## What

* Add releases
   * One way is using [goreleaser](https://github.com/goreleaser/goreleaser)

## Why

Although, there are install script `install_cli.sh`, it doesn't work because there are no releases yet.

```
filename="ap-${OS}-amd64"
url="https://github.com/solo-io/autopilot/releases/download/${AP_VERSION}/${filename}"
```

**Comment by ilackarms** [comment] 2019-12-10 14:50
Sorry, this issue was caused by the indentation problem you fixed. Thank you @KeisukeYamashita !

Just to be transparent, Autopilot is still in an alpha stage and a refactor is in the process with a set of new features (including `multicluster` support) here: https://github.com/solo-io/autopilot/tree/rearch

**Comment by ilackarms** [comment] 2019-12-10 14:50
Closing for now, please reopen if the issue persists

**Closed by ilackarms** 2019-12-10 14:50 UTC

**Comment by KeisukeYamashita** [comment] 2019-12-12 16:57
Thank you!
